"""add_spend_group_to_targets

Revision ID: c7a6a18d3992
Revises: 89009da382eb
Create Date: 2026-05-24 21:45:50.394887

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a6a18d3992'
down_revision: Union[str, None] = '89009da382eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spend_group', sa.String(length=20), nullable=False, server_default='necessary'))

    targets = sa.table('targets', sa.column('id', sa.Integer), sa.column('name', sa.String), sa.column('spend_group', sa.String))
    group_map = {
        'income': ['Household Income'],
        'necessary': ['Mortgage', 'Insurance', 'Utilities', 'Internet', 'Groceries', 'Gas'],
        'discretionary': ['Fast Food', 'Dining Out', 'Shopping', 'Subscriptions', 'Entertainment', 'Home Improvement'],
    }
    for group, names in group_map.items():
        op.execute(targets.update().where(targets.c.name.in_(names)).values(spend_group=group))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_column('spend_group')

    # ### end Alembic commands ###
